"""RTKLIB configuration file parser."""

from typing import Any


class ConfigParser:
    """Parser for RTKLIB configuration files."""

    def parse(self, content: str) -> dict[str, Any]:
        """Parse RTKLIB configuration file content.

        Args:
            content: Configuration file content as string

        Returns:
            Dictionary of configuration settings

        Raises:
            ValueError: If the configuration format is invalid
        """
        settings: dict[str, Any] = {}

        for line_num, line in enumerate(content.splitlines(), 1):
            line = line.strip()

            # Skip empty lines and comments
            if not line or line.startswith("#"):
                continue

            # Parse key=value pairs
            if "=" not in line:
                continue

            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()

            # Remove inline comments
            if "#" in value:
                value = value.split("#")[0].strip()

            # Try to convert value to appropriate type
            settings[key] = self._convert_value(value)

        return settings

    def _convert_value(self, value: str) -> str | int | float | bool:
        """Convert string value to appropriate Python type."""
        # Boolean
        if value.lower() in ("on", "true", "yes", "1"):
            return True
        if value.lower() in ("off", "false", "no", "0"):
            return False

        # Integer
        try:
            return int(value)
        except ValueError:
            pass

        # Float
        try:
            return float(value)
        except ValueError:
            pass

        # Keep as string
        return value

    def export(self, settings: dict[str, Any]) -> str:
        """Export settings to RTKLIB configuration format.

        Args:
            settings: Dictionary of configuration settings

        Returns:
            Configuration file content as string
        """
        lines = ["# RTKLIB Configuration File", "# Generated by RTKLIB Web UI", ""]

        for key, value in sorted(settings.items()):
            if isinstance(value, bool):
                value_str = "on" if value else "off"
            else:
                value_str = str(value)
            lines.append(f"{key}={value_str}")

        lines.append("")  # Trailing newline
        return "\n".join(lines)
