/**
 * Convert frontend MrtkPostConfig (camelCase) to backend-compatible
 * snake_case dict for API calls.
 */
import type { MrtkPostConfig } from '../types/mrtkPostConfig';

export function configToBackend(config: MrtkPostConfig): Record<string, unknown> {
  const p = config.positioning;
  const ar = config.ambiguityResolution;
  const kf = config.kalmanFilter;
  const ant = config.antenna;
  return {
    positioning: {
      positioning_mode: p.positioningMode,
      frequency: p.frequency,
      signal_mode: p.signalMode,
      signals: p.signals,
      filter_type: p.filterType,
      elevation_mask: p.elevationMask,
      receiver_dynamics: p.receiverDynamics,
      ephemeris_option: p.ephemerisOption,
      constellations: p.constellations,
      excluded_satellites: p.excludedSatellites,
      snr_mask: {
        enable_rover: p.snrMask.enableRover,
        enable_base: p.snrMask.enableBase,
        mask: p.snrMask.mask,
      },
      corrections: {
        satellite_antenna: p.corrections.satelliteAntenna,
        receiver_antenna: p.corrections.receiverAntenna,
        phase_windup: p.corrections.phaseWindup,
        exclude_eclipse: p.corrections.excludeEclipse,
        raim_fde: p.corrections.raimFde,
        iono_compensation: p.corrections.ionoCompensation,
        partial_ar: p.corrections.partialAr,
        shapiro_delay: p.corrections.shapiroDelay,
        exclude_qzs_ref: p.corrections.excludeQzsRef,
        no_phase_bias_adj: p.corrections.noPhaseBiasAdj,
        gps_frequency: p.corrections.gpsFrequency,
        qzs_frequency: p.corrections.qzsFrequency,
        tidal_correction: p.corrections.tidalCorrection,
      },
      atmosphere: {
        ionosphere: p.atmosphere.ionosphere,
        troposphere: p.atmosphere.troposphere,
      },
      clas: {
        grid_selection_radius: p.clas.gridSelectionRadius,
        receiver_type: p.clas.receiverType,
        position_uncertainty_x: p.clas.positionUncertaintyX,
        position_uncertainty_y: p.clas.positionUncertaintyY,
        position_uncertainty_z: p.clas.positionUncertaintyZ,
      },
    },
    ambiguity_resolution: {
      mode: ar.mode,
      gps_ar: ar.gpsAr,
      glonass_ar: ar.glonassAr,
      bds_ar: ar.bdsAr,
      qzs_ar: ar.qzsAr,
      thresholds: {
        ratio: ar.thresholds.ratio,
        ratio1: ar.thresholds.ratio1,
        ratio2: ar.thresholds.ratio2,
        ratio3: ar.thresholds.ratio3,
        ratio4: ar.thresholds.ratio4,
        ratio5: ar.thresholds.ratio5,
        ratio6: ar.thresholds.ratio6,
        alpha: ar.thresholds.alpha,
        elevation_mask: ar.thresholds.elevationMask,
        hold_elevation: ar.thresholds.holdElevation,
      },
      counters: {
        lock_count: ar.counters.lockCount,
        min_fix: ar.counters.minFix,
        max_iterations: ar.counters.maxIterations,
        out_count: ar.counters.outCount,
      },
      partial_ar: {
        min_ambiguities: ar.partialAr.minAmbiguities,
        max_excluded_sats: ar.partialAr.maxExcludedSats,
        min_fix_sats: ar.partialAr.minFixSats,
        min_drop_sats: ar.partialAr.minDropSats,
        min_hold_sats: ar.partialAr.minHoldSats,
        ar_filter: ar.partialAr.arFilter,
      },
      hold: {
        variance: ar.hold.variance,
        gain: ar.hold.gain,
      },
    },
    rejection: {
      innovation: config.rejection.innovation,
      l1_l2_residual: config.rejection.l1L2Residual,
      dispersive: config.rejection.dispersive,
      non_dispersive: config.rejection.nonDispersive,
      hold_chi_square: config.rejection.holdChiSquare,
      fix_chi_square: config.rejection.fixChiSquare,
      gdop: config.rejection.gdop,
      pseudorange_diff: config.rejection.pseudorangeDiff,
      position_error_count: config.rejection.positionErrorCount,
    },
    slip_detection: {
      threshold: config.slipDetection.threshold,
      doppler: config.slipDetection.doppler,
    },
    kalman_filter: {
      iterations: kf.iterations,
      sync_solution: kf.syncSolution,
      measurement_error: {
        code_phase_ratio_l1: kf.measurementError.codePhaseRatioL1,
        code_phase_ratio_l2: kf.measurementError.codePhaseRatioL2,
        code_phase_ratio_l5: kf.measurementError.codePhaseRatioL5,
        phase: kf.measurementError.phase,
        phase_elevation: kf.measurementError.phaseElevation,
        phase_baseline: kf.measurementError.phaseBaseline,
        doppler: kf.measurementError.doppler,
        ura_ratio: kf.measurementError.uraRatio,
      },
      initial_std: {
        bias: kf.initialStd.bias,
        ionosphere: kf.initialStd.ionosphere,
        troposphere: kf.initialStd.troposphere,
      },
      process_noise: {
        bias: kf.processNoise.bias,
        ionosphere: kf.processNoise.ionosphere,
        iono_max: kf.processNoise.ionoMax,
        troposphere: kf.processNoise.troposphere,
        accel_h: kf.processNoise.accelH,
        accel_v: kf.processNoise.accelV,
        position_h: kf.processNoise.positionH,
        position_v: kf.processNoise.positionV,
        position: kf.processNoise.position,
        ifb: kf.processNoise.ifb,
        iono_time_const: kf.processNoise.ionoTimeConst,
        clock_stability: kf.processNoise.clockStability,
      },
    },
    antenna: {
      rover: {
        mode: ant.rover.mode,
        values: ant.rover.values,
        antenna_type_enabled: ant.rover.antennaTypeEnabled,
        antenna_type: ant.rover.antennaType,
        antenna_delta: ant.rover.antennaDelta,
      },
      base: {
        mode: ant.base.mode,
        values: ant.base.values,
        antenna_type_enabled: ant.base.antennaTypeEnabled,
        antenna_type: ant.base.antennaType,
        antenna_delta: ant.base.antennaDelta,
      },
    },
    output: {
      solution_format: config.output.solutionFormat,
      output_header: config.output.outputHeader,
      output_processing_options: config.output.outputProcessingOptions,
      time_format: config.output.timeFormat,
      num_decimals: config.output.numDecimals,
      lat_lon_format: config.output.latLonFormat,
      field_separator: config.output.fieldSeparator,
      output_velocity: config.output.outputVelocity,
      geoid_model: config.output.geoidModel,
      static_solution_mode: config.output.staticSolutionMode,
      output_single_on_outage: config.output.outputSingleOnOutage,
      nmea_interval_rmc_gga: config.output.nmeaIntervalRmcGga,
      nmea_interval_gsa_gsv: config.output.nmeaIntervalGsaGsv,
      output_solution_status: config.output.outputSolutionStatus,
      debug_trace: config.output.debugTrace,
    },
    files: {
      satellite_atx: config.files.satelliteAtx,
      receiver_atx: config.files.receiverAtx,
      station_pos: config.files.stationPos,
      geoid: config.files.geoid,
      ionosphere: config.files.ionosphere,
      dcb: config.files.dcb,
      eop: config.files.eop,
      ocean_loading: config.files.oceanLoading,
      elevation_mask_file: config.files.elevationMaskFile,
      fcb: config.files.fcb,
      bias_sinex: config.files.biasSinex,
      cssr_grid: config.files.cssrGrid,
      isb_table: config.files.isbTable,
      phase_cycle: config.files.phaseCycle,
    },
    adaptive_filter: {
      enabled: config.adaptiveFilter.enabled,
      iono_forgetting: config.adaptiveFilter.ionoForgetting,
      iono_gain: config.adaptiveFilter.ionoGain,
      pva_forgetting: config.adaptiveFilter.pvaForgetting,
      pva_gain: config.adaptiveFilter.pvaGain,
    },
    signal_selection: config.signalSelection,
    receiver: {
      iono_correction: config.receiver.ionoCorrection,
      ignore_chi_error: config.receiver.ignoreChiError,
      bds2_bias: config.receiver.bds2Bias,
      ppp_sat_clock_bias: config.receiver.pppSatClockBias,
      ppp_sat_phase_bias: config.receiver.pppSatPhaseBias,
      uncorr_bias: config.receiver.uncorrBias,
      max_bias_dt: config.receiver.maxBiasDt,
      satellite_mode: config.receiver.satelliteMode,
      phase_shift: config.receiver.phaseShift,
      isb: config.receiver.isb,
      reference_type: config.receiver.referenceType,
      max_age: config.receiver.maxAge,
      baseline_length: config.receiver.baselineLength,
      baseline_sigma: config.receiver.baselineSigma,
    },
    server: {
      cycle_ms: config.server.cycleMs ?? 10,
      timeout_ms: config.server.timeoutMs ?? 10000,
      reconnect_ms: config.server.reconnectMs ?? 10000,
      nmea_cycle_ms: config.server.nmeaCycleMs ?? 5000,
      buffer_size: config.server.bufferSize ?? 32768,
      nav_msg_select: config.server.navMsgSelect ?? 'all',
      proxy: config.server.proxy ?? '',
      swap_margin: config.server.swapMargin ?? 30,
      time_interpolation: config.server.timeInterpolation ?? false,
      sbas_satellite: config.server.sbasSatellite ?? '0',
      rinex_option_1: config.server.rinexOption1 ?? '',
      rinex_option_2: config.server.rinexOption2 ?? '',
      ppp_option: config.server.pppOption ?? '',
      rtcm_option: config.server.rtcmOption ?? '',
      l6_margin: config.server.l6Margin ?? 0,
      max_obs_loss: config.server.maxObsLoss ?? 90.0,
      float_count: config.server.floatCount ?? 15,
    },
  };
}
